= Esa ja Jari 2/1
:toc:
:toc-title: Sisällysluettelo

++++
<a href="index.html" class="back-link">← Kaikki systeemit</a>
++++

== Yhden tason avausten jatkoja

=== Perussarjoja

[.top]
|===
| Avaus  | Vastaus | Jatko
| 1 &clubs; = 2+&clubs;, 11+p
|1 [red]#&diams;# = 4+[red]#&hearts;# 6+p, +
1 [red]#&hearts;# = 4+&spades;, 6+p, +
1 &spades; = 4+[red]#&diams;#, 6+p +
1 NT = tas., 6-10p,  +
2 [red]#&diams;# = 5+ &clubs;, criss cross, tpv +
2&clubs; = 5+&clubs;, yleensä epätas. 5-10p +
2NT = tasainen, 11-12p +
3&clubs; = 5+&clubs;, yleensä epätas. 11-12p +
3 [red]#&diams;# / 3 [red]#&hearts;# / 3&spades; = splitteri +
4+ &clubs; = 5+ &clubs; esto
| 1 [red]#&diams;#, 1 [red]#&hearts;#  katso Transfer Walsh

|1 [red]#&diams;# = 4+[red]#&diams;#, 11+p +
|1 [red]#&hearts;# = 4+[red]#&hearts;#, 6+p +
1 &spades; = 4+&spades;, 6+p +
1NT = 6-10p +
2&clubs; = 4+&clubs;, tpv +
2 [red]#&diams;# = 4+ [red]#&diams;#, 6-10p +
2NT = tasainen, 11-12p +
3 &clubs; = 4+ [red]#&diams;#, criss cross, tpv +
3 [red]#&diams;# = 4+ [red]#&diams;#, yleensä epätas., 11-12p
| 2 [red]#&hearts;# = 5+ [red]#&hearts;#, min +

| 1 [red]#&hearts;# = 5+[red]#&hearts;#, 11+p
| 1 &spades; = 4+ &spades; , 6+p +
1NT = ei 3 [red]#&hearts;#, 6 - 11(12)p +
2&clubs; = 4+&clubs; tpv +
2 [red]#&diams;# = 4+&clubs; tpv +
2 [red]#&hearts;# = 3+[red]#&hearts;#, 6-10p +
2NT = 4+ [red]#&hearts;#, Jacoby 2NT, tpv +
3&clubs; = 6+&clubs;, 0-2 [red]#&hearts;#, 11-12p +
3 [red]#&diams;# = 6+ [red]#&diams;#, 0-2 [red]#&hearts;#, 11-12p +
3 [red]#&hearts;# = 3+ [red]#&hearts;#, inviitti, 10-12p, +
3&spades; / 4 &clubs; / 4 [red]#&diams;# =  splintteri +
4 [red]#&hearts;# = 5+[red]#&hearts;#, esto,  0 - 8p +
4&spades; = 7+ &spades;, pelattavaksi, enintään 10p +
|

| 1 &spades; = 5+ &spades;, 11+p
|1NT = ei tukea, 6-11(12) +
2&clubs; = 3+&clubs;, tpv +
2 [red]#&diams;# = 4+ [red]#&diams;#, tpv +
2 [red]#&hearts;# = 5+ [red]#&hearts;#, tpv +
2NT = 4+ &spades;, Jacoby 2NT, tpv +
3 &clubs; = 6+ &clubs;, 0-2 &spades;,  11-12p +
3 [red]#&diams;# = 6+ [red]#&diams;#, 0-2 &spades;, 11-12p +
3 [red]#&hearts;# = 6+[red]#&hearts;#, 0-2 &spades;, 11-12p +
3 &spades; = 3+ &spades;, inviitti, 11-12p +
4 &clubs; / 4 [red]#&diams;# / 4 [red]#&hearts;# = splintteri, 11-15p +
4 &spades; = 5+ &spades;, esto, 0-8p
|

|===

=== 2/1-sarjoja


|===
| Alku | Avaajan 2.

| 1 &spades; - 2 &clubs;
| 2 &spades; = min tai 15-16, ei lupaa lisäpituutta +
  2NT = sivupidot, 12-14 tai 18-19 +
  3 &clubs; = ei lyhyyttä, ekstraa +
  3 [red]#&diams;# = tuki, lyhyys ruudussa, ekstraa +
  3 [red]#&hearts;# = tuki, lyhyys hertassa, ekstraa +
  3 &spades; = 6+ &spades, 15-16
|===


=== Yläväritrialit

==== ruutuavauksen jälkeen

|===
| Alku | Vastaajan 2. | Avaajan 3.

| 1 [red]#&diams;# - 1 [red]#&hearts;# - 2 [red]#&hearts;#
| 2 &spades; = kysyy tuen pituutta ja voimaa +
| 2NT = 3k tuki, min +
  3 &clubs; = 3k tuki, max +
  3 [red]#&diams;#  = 4k tuki min +
  3 [red]#&hearts;#  = 4k tuki max

| 1 [red]#&diams;# - 1 &spades; - 2 &spades;
| 2NT = kysyy tuen pituutta ja voimaa
| 3 &clubs; = 3k tuki, min +
  3 [red]#&diams;#, max +
  4  [red]#&hearts;# = 4k tuki, min +
  4  &spades; = 4k tuki, max

|===

==== Kokish


|===
| Alku | Avaajan 2. | Vastaajan 2.

| 1 [red]#&hearts;# - 2 [red]#&hearts;#
| 2 &spades; = kysyy missä apuja
| väri kertoo avun ja 3 [red]#&hearts;#  kieltää avut

|
| 2NT = patalyhyys, inv+ +
  3 &clubs; = ristilyhyys, inv+ +
  3 [red]#&diams;# = ruutulyhyys, inv+ +
|

| 1 &spades; - 2 &spades;
| 2NT = kysyy apuja
| väri kertoo avun ja 3 &spades; kieltää avut

|
| 3 &clubs; = ristilyhyys, inv+ +
  3 [red]#&diams;# = ruutulyhyys, inv+ +
  3 [red]#&hearts;# = herttalyhyys, inv+ +
|

|===

=== Hyppysangin jälkeen

|===
| Alku | Vastaajan 2.

| 1x - 1y - 2NT = hyppysangi
| 3 &clubs; = ruutusiirto +
  3 [red]#&hearts;# = patasiirto +
  3 &spades; = ristisiirto +
  4 &clubs; = Gerber!
|===



=== Criss cross -jatkot

|===
| Alku | Avaajan 2.


| 1 [red]#&diams;#  - 3 &clubs; = 4+ [red]#&diams;# , tpv
| 3 [red]#&diams;# = minimi, ei lyh., 12-14 tai 17-21 +
  3  [red]#&hearts;#  / 3 &spades; / 4 &clubs; = lyhyys värissä, 11+ +
  3NT = 12-14 tasainen +
  4 [red]#&diams;#  = slammihakuinen, ei lyh.

| 1 &clubs; - 2 [red]#&diams;# = 5+ &clubs;, tpv
| 2 [red]#&diams;# / 2 [red]#&hearts;# / 2 &spades; = lyhyys, 12+ +
  2NT = sivupidot, minimi tai ekstraa ja ei hyppysangi +
  3 &clubs; = ei lyhyyttä, minimi tai ekstraa ja ei hyppysangi
  3NT = hyppysangi, 18-19

|===

=== Solowayn vahvat hypyt

http://kwbridge.com/js.htm

Soloway-hypyt ovat yksinkertaisia hyppyjä uudessa värissä.
Hyppääjällä on joku seuraavista käsityypeistä:

1. Vahva 6+k vahva väri, jossa kaksi toppikuvaa kolmesta, 17 - 19
2. Oma pitkä solidi väri (AKQ)ja hyvät kontrollit, 13-16
3. Vahva 5k väri, 5x332, 17-19
4. Oma hyvä 5k väri ja tuki avausväriin, 16+. Hyppääjä kertoo tässä tapauksessa
missä lyhyys on, jos mahdollista.

|===
|Avaus |Vastaus |Avaajan 2. |Vastaajan 2.

|1 [red]#&diams;#
|2 [red]#&hearts;#
| 2NT = tas. minimi ja sivupidot +
  3 [red]#&diams;# = lisäpituutta ja voimaa värissä +
  3 &clubs; / 3  &spades;  = voimaa värissä +
  3 [red]#&hearts;# = 2+ [red]#&hearts;# , väh. yksi kolmesta toppikuvasta
| 3 [red]#&diams;# = 5 [red]#&hearts;#, 4 [red]#&diams;#, ei lyhyyttä, 16+ +
3 [red]#&hearts;# = 6+ [red]#&hearts;# , 17 - 19 +
3 &spades; = patalyhyys ja 5 [red]#&hearts;#, 4 [red]#&diams;#, 16+ +
3NT = 5 [red]#&hearts;# 332, 17 - 19 +
4 [red]#&hearts;# = 6+ [red]#&hearts;# , AKQ hertassa, 13-16

|===


=== Transfer Walsh

Tämä sopimus ei muuta luonnollisesta systeemistä kuin kolmen kortin
tuen ilmaisun, kun avaajalla on tasainen minimi tai epätasainen käsi.
Epätasaisen käden vaihtelevan voiman takia kolmen kortin tuen näyttäminen
on vaatimus vastaajalle. Kaikki muut tarjoukset säilyvät ennallaan.
Transfer Walsh on voimassa kahdennuksen jälkeenkin.

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 &clubs;
| 1 [red]#&diams;# = 4+ [red]#&hearts;#, 6+p
| 1 [red]#&hearts;# = tasan 3 [red]#&hearts;#, vaatimus +
2 [red]#&hearts;# = 4 [red]#&hearts;#, 11-15p, ei vaat. +
2 &spades; = 0-2 [red]#&hearts;#, reverse +
2NT = tas., 2-3 [red]#&hearts;#, 18-19p +
3 &clubs; = 0-2 [red]#&hearts;#, 6+ &clubs;, 16-18p +
3 [red]#&diams;#, 3&spades; = 0-1 [red]#&diams;# / &spades;, 4 [red]#&hearts;#, tpv +
3 [red]#&hearts;# = 4 [red]#&hearts;#, 16-18p

| 2 [red]#&hearts;# = 5+ [red]#&hearts;#, 6-10p +

| 1 &clubs;
| 1 [red]#&hearts;# = 4+ &spades;, 6+p
| 1 &spades; = tasan 3&spades;, vaat. +
2 &spades; = 4 &spades;, 11-15p +
2NT = tas., 2-3 &spades;, 18-19p +
3 &clubs; = 0-2 , 6+ &clubs;, 1&spades; 6-18p +
3 [red]#&diams;#, [red]#&hearts;# = 0-1 [red]#&diams;# / [red]#&hearts;#, 4 &spades;, tpv +
3 &spades; = 4 &spades;, 16-18p
|
|===

=== Lisää 2/1-sarjoista esimerkein

Alla esimerkkejä sarjoista, joiden kanssa analogiset sarjat
saavat saman merkityksen.

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 [red]#&hearts;#
| 2&clubs;
| 2 [red]#&hearts;# = min ja ei sivupitoja tai 17+
|

|===

=== 1 [red]#&hearts;# / &spades; - 2NT -jatkot
Sopimus on voimassa kahdennuksen jälkeenkin, mutta ei muuten.
|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 [red]#&hearts;#
| 2NT = 4+ [red]#&hearts;#, 13+, tpv
| 3&clubs; / 3 [red]#&diams;# / 3 &spades; = lyhyys tarjotussa värissä, 11+ +
  3 [red]#&hearts;# = 6+ [red]#&hearts;# 15+, ei lyhyyttä
  3NT = 5 [red]#&hearts;# 422, 16-18 +
  4 &clubs; / [red]#&diams;# = vahva sivuväri, 11+ +
  4 [red]#&hearts;# = minimi, ei lyhyyttä
| 3 [red]#&hearts;# = pyytää cueta, muut cue-tarjouksia, ekstraa. 4 [red]#&hearts;# = minimi

| 1 &spades;
| 2NT = 4+ &spades; = 13+
| 3&clubs; / 3 [red]#&diams;# / 3 [red]#&hearts;# = lyhyys tarjotussa värissä, 11+ +
3 &spades; = 6+ &spades; 15+, ei lyhyyttä
3NT = 5 &spades; 422, 16-18 +
4 &clubs; / [red]#&diams;# / [red]#&hearts;# = vahva sivuväri, 11+ +
4 [red]#&hearts;# = minimi, ei lyhyyttä
| 3 &spades; = pyytää cueta, muut cue-tarjouksia, ekstraa. +
  4 &spades; = minimi

|===




=== Xyz -- 1x - 1y - 1z

Xyz-sopimuksella tarjotaan aina kaikki tasaiset ja oman värin
inviitit. Sopimus ei ole voimassa, jos vastustaja tekee muuta kuin
passaa. Xyz tarkoittaa mitä tahansa yhden tasolla tapahtuvaa sarjaa, jossa
on kolme tarjousta ja jatko on seuraava.

|===
| Avaaja | Vastaus | Avaaja 2. | Vastaaja 2.

| 1x - 1y - 1z
| 2 &clubs; = pyytää 2 [red]#&diams;#. Tekee myöhemmin inviitin
 tai passaa 2 [red]#&diams;# tarjoten oman ruutuvärin +

 2 [red]#&diams;# = keinotekoinen tpv, pyytää kuvaamaan kättä +

 2NT = pyytää tarjoamaan 3 &clubs;, mihin passataan
| 2 [red]#&diams;#
| Vastaajan värin toisto = inviitti 5+k värillä

|===

==== Esimerkki
1 [red]#&diams;# - 1 [red]#&hearts;#; 1NT - 2&clubs; ; 2 [red]#&diams;# - 2 [red]#&hearts;# = yleensä 6+
[red]#&hearts;# ja 11-12p.

== 1NT-jatkot

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

|1NT = tas. 15-17
| 2&clubs; = Stayman
| 2 [red]#&diams;# = ei 4yv
| 2 [red]#&hearts;# = 5 [red]#&hearts;# 4 &spades;, inv. +
2 &spades; = 5 &spades;, 4 [red]#&hearts;#, inv +
3&clubs; = 5+&clubs;, tpv +
3 [red]#&diams;# = 5+ [red]#&diams;#, tpv +
3 [red]#&hearts;# = 5+ &spades;, 4 [red]#&hearts;#, tpv +
3 &spades; = 5+ [red]#&hearts;#, 4&spades;, tpv

|
| 2 [red]#&diams;# = 5+ [red]#&hearts;#, siirto
| 2 [red]#&hearts;# = 2+ [red]#&hearts;# +
3 [red]#&hearts;# = 4+[red]#&hearts;#, max
|

|
| 2 [red]#&hearts;# = 5+ &spades;, siirto +
| 2 &spades; = 2+ &spades; +
3 &spades; = 4+&spades;, max
|

|
| 2 &spades; = 6+&clubs;, kysyy max
| 2NT = min, 3&clubs; = 3+&clubs; max
|

|
| 3&clubs; = 6+ [red]#&diams;#, siirto
| 3 [red]#&diams;# = siirto vastaan
| 3yv = lyhyys yv:ssä +
3NT = 15-16p, ei lyhyyksiä

|
| 3 [red]#&hearts;# = 3&spades; 1 [red]#&hearts;# av:t 5-4, tpv
|
|

|
| 3&spades; = 3 [red]#&hearts;# 1 &spades; av:t 5-4, tpv
|
|

|
| 4&clubs; = Gerber
| 4 [red]#&diams;# = 0 / 4 +
4 [red]#&hearts;# = 1 +
4 &spades; = 2 +
4NT = 3
|

|
| 4 [red]#&diams;# = 6+ [red]#&hearts;# (aina voimassa)
|
|

|
| 4 [red]#&hearts;# = 6+&spades; (aina voimassa)
|
|

|
| 4NT = 16-17p, kvantti
|
|

|===

== Heikkojen kakkosten triali


|===
| Alku | Avaajan 2.

| 2 [red]#&diams;# / 2 [red]#&hearts;# / 2 &spades; - 2NT = kysyy
| avausvärin toisto = ei lyh. +
  uusi väri = lyhyys +
  3NT = ei lyhyyttä, solidi avausväri
|===

== Drury vain 3. penkissä


|===
|Avaaja |Vastaaja |Avaajan 2. |Vastaajan 2.

| P - (P) - 1 [red]#&hearts;#
| 2 &clubs; = 3+ [red]#&hearts;#, inv+
| 2 [red]#&diams;# = normaali avaus, min +
  2 [red]#&hearts;#  = heikko 3. käden avaus +
  Muut avaajan tarjoukset Kokish-trial-logiikalla
|
|===

== Kun vastustaja välitarjoaa

=== Tukikahdennus

Avaaja näyttää vastaajan yläväritarjoukseen 3k tuen kahdennuksella. Jos
tukikahdennus tehdään kolmen tasolla, niin se lupaa lisävoimaa ollen
mahdollisesti rankkariluonteinen.

=== Esimerkkejä

Alla tarjoukset esimerkein. Muut tapaukset käsitellään
vastaavasti.

|===
| Avaaja | Vastustaja | Vastaaja

| 1 [red]#&diams;#
| Dbl
| Rdbl = 11+, rangaistusluonteinen, ei tukea

|
| 1 [red]#&hearts;#
| Dbl = 4 &spades;, 7+ +
  1 &spades; = 5+ &spades;, 6+ +
  1NT = 6 - 10 +
  2 &clubs; = 5+ &clubs;, 11+ +
  2 [red]#&diams;# = 4+, 6 - 10 +
  2 [red]#&hearts;# = 4+ [red]#&diams;#, 11+ +
  2NT = pito hertassa, 11-12, ei tukea +
  3 [red]#&hearts;# = 0-1 [red]#&hearts;#, 4+[red]#&diams;#, usein slammihakuinen, tpv


|===


|===
| Ässäkysely | Vastaus | Kysyjän 2. tarjous | Vastaajan 2.

| 4NT
| 5 &clubs; = 1 tai 4 avainkorttia viidestä +
  5 [red]#&diams;# =  0 tai 3 avainkorttia viidestä +
  5 [red]#&hearts;# = 2 tai 5 avainkorttia viidestä ja ei valttirouvaa
  5  &spades;  = 2 tai 5 avainkorttia viidestä ja valttirouva

| alin vapaa kysyy rouvaa
| - negatiivi tarjoaa alimman valttitarjouksen +
  - kuningas tarjotussa värissä ja rouva +
  - 5NT = rouva, ei kuningasta tarjottavissa alle 6 valttia


|===

== 1NT - puolustus


|===
| Vastustaja | Me | Jatko

| 1NT
| Dbl = 16+
|

|
| 2&clubs; = ylävärit vähintään 5-4, 9+
| 2  [red]#&diams;#  = yhtä pitkät ylävärit, valitse

|
| 2 [red]#&diams;# = 6k yläväri, 9+
| Kuten Multi-avauksessa: 2yv

|
| 2 [red]#&hearts;# = 4 [red]#&hearts;# + 5k alaväri
|

|
| 2 &spades; = 4 &spades;  + 5k alaväri
|

|===

== Puolustustarjouksia


=== Michael's cue


|===
| Vastustajan 1. | Meidän 1. | Meidän 2.

| 1 &clubs; = 2+ &clubs;
| 2 &clubs; = ylävärit 5-5, avausvoima
| 3 &clubs; = inv+ hertassa +
  3  [red]#&diams;#  = inv+ padassa

| 1 [red]#&diams;# = 2+ [red]#&diams;#
| 2 [red]#&diams;# = ylävärit 5-5, avausvoima
| 3 &clubs; = inv+ hertassa +
 3 [red]#&diams;# = inv+ padassa +
|===

=== Unusual 2NT

Hyppäävä 2NT välitarjous lupaa alimmat tarjoamattomat värit 5-5.

=== Leaping Micheael's

Leaping Michael's lupaa hyvän käden ja tarjoamattomat värit
5-5: ylävärit tai ylävärin ja alavärin.
