
= Esa ja Kalle 2/1
:toc:

== Avaukset


|===
| Avaus | Vastaus

| 1 &clubs; = 2+ &clubs; , 11+
|

| 1 [red]#&#9670;# = 4+ [red]#&#9670;# , 11+
|

| 1 [red]#&hearts;# = 5+ [red]#&hearts;# , 11+
|

| 1 &spades; = 5+ &spades; , 11+
|

| 1NT = 15 - 17,  5k yv mahdollinen
|

| 2 &clubs; = 22+
|

| 2 [red]#&#9670;# = 6 [red]#&#9670;# , 6 - 10
|

| 2 [red]#&hearts;# = 6 [red]#&hearts;# , 6- 10
|

| 2 &spades; = 6 &spades; , 6 - 10
|

| 2NT = tasainen, 20 - 21
|

| 3 &clubs; = 7  &clubs; , 6 - 10
|

| 3 [red]#&#9670;# = 7 [red]#&#9670;# , 6 - 10
|

| 3 [red]#&hearts;# = 7 [red]#&hearts;# , 6- 10
|

| 3 &spades; = 7 &spades; , 6 - 10
|

| 4 &clubs; = 7 - 8  &clubs; , 6 - 10
|

| 4 [red]#&#9670;# = 7 - 8 [red]#&#9670;# , 6 - 10
|

| 4 [red]#&hearts;# = 7 - 8 [red]#&hearts;# , 6 - 10
|

| 4 &spades; = 7 -8 &spades; , 6 - 10
|

|===

== Yhden tason avausten jatkoja

|===
| Avaus  | Vastaus | Jatko
| 1 &clubs; = 2+&clubs;, 11+p
|1 [red]#&#9670;# = 4+[red]#&hearts;# 6+p, +
1 [red]#&hearts;# = 4 +&spades;, 6+p, +
1 &spades; = 4+[red]#&#9670;#, 6+p +
1 NT = tas. ei 4k yv, 6-10p,  +
2 [red]#&#9670;# = 5+ &clubs; yleensä tasaisehko,  tpv +
2&clubs; = 5+&clubs;, ei 4k yv., yleensä epätas. 5-10p +
2NT = tasainen, ei 4k yv, 11-12p +
3&clubs; = 5+&clubs;, ei 4k yv., yleensä epätas. 11-12p +
3 [red]#&#9670;# / 3 [red]#&hearts;# / 3&spades; = 5+&clubs; ei 4k yv, 0-1 tarjouttua väriä, tpv
4+ &clubs; = 5+ &clubs; ei 4k yv, esto
| 1 [red]#&#9670;#, 1 [red]#&hearts;#  katso <<_transfer_walsh>>

|1 [red]#&#9670;# = 4+[red]#&#9670;#, 11+p +
|1 [red]#&hearts;# = 4+[red]#&hearts;#,  6+p +
1 &spades; = 4+&spades;, 6+p +
1NT = ei 4k yv, 6-10p +
2&clubs; = 4+&clubs;, tpv +
2 [red]#&#9670;# = 4+ [red]#&#9670;#, 6-10p +
2NT = tasainen, ei 4k yv, 11-12p +
3 &clubs; = 4+ [red]#&#9670;# yleensä tasaisehko, ei 4k yv, tpv +
3 [red]#&#9670;# = 4+ [red]#&#9670;#, yleensä epätas., 11-12p
| 2 [red]#&hearts;# = 5+ [red]#&hearts;#, min +

| 1 [red]#&hearts;# = 5+[red]#&hearts;#, 11+p
| 1 &spades; = 4+ &spades; , 6+p +
1NT = ei 3 [red]#&hearts;#, 6 - 11(12)p +
2&clubs; = 4+&clubs; tpv +
2 [red]#&#9670;# = 4+&clubs; tpv +
2 [red]#&hearts;# = 3+[red]#&hearts;#, 6-10p +
2NT = 4+ [red]#&hearts;#, <<Jacoby 2NT>>, tpv +
3&clubs; = 6+&clubs;, 0-2 [red]#&hearts;#, 11-12p +
3 [red]#&#9670;# = 6+ [red]#&#9670;#, 0-2 [red]#&hearts;#, 11-12p +
3 [red]#&hearts;# = 3+ [red]#&hearts;#, inviitti, 10-12p, +
3&spades; / 4 &clubs; / 4 [red]#&#9670;# = 4+ [red]#&hearts;#, splintteri, 0-1 tarjottua väriä, 11-15p (paremmalla 2NT) +
4 [red]#&hearts;# = 5+[red]#&hearts;#, esto,  0 - 8p +
4&spades; = 7+ &spades;, pelattavaksi, enintään 10p +
|

| 1 &spades; = 5+ &spades;, 11+p
|1NT = ei tukea, 6-11(12) +
2&clubs; = 3+&clubs;, ei kiellä 3k tukea, tpv +
2 [red]#&#9670;# = 4+ [red]#&#9670;#, ei kiellä 3k tukea, tpv +
2 [red]#&hearts;# = 5+ [red]#&hearts;#, tpv +
2NT = 4+ &spades;, <<Jacoby 2NT>>, tpv +
3 &clubs; = 6+ &clubs;, 0-2 &spades;,  11-12p +
3 [red]#&#9670;# = 6+ [red]#&#9670;#, 0-2 &spades;, 11-12p +
3 [red]#&hearts;# = 6+[red]#&hearts;#, 0-2 &spades;, 11-12p +
3 &spades; = 3+ &spades;, inviitti, 11-12p +
4 &clubs; / 4 [red]#&#9670;# / 4 [red]#&hearts;# = 4+ &spades;, splintteri, 11-15p +
4 &spades; = 5+ &spades;, esto, 0-8p
|


|===


=== Transfer Walsh

Tämä sopimus ei muuta luonnollisesta systeemistä kuin kolmen kortin
tuen ilmaisun, kun avaajalla on tasainen minimi tai epätasainen käsi.
Epätasaisen käden vaihtelevan voiman takia kolmen kortin tuen näyttäminen
on vaatimus vastaajalle. Kaikki muut tarjoukset säilyvät ennallaan.
Transfer Walsh on voimassa kahdennuksen jälkeenkin.

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 &clubs;
| 1 [red]#&#9670;# = 4+ [red]#&hearts;#, 6+p
| 1 [red]#&hearts;# = tasan 3 [red]#&hearts;#, vaatimus +
2 [red]#&hearts;# = 4 [red]#&hearts;#, 11-15p, ei vaat. +
2 &spades; = 0-2 [red]#&hearts;#, reverse +
2NT = tas., 2-3 [red]#&hearts;#, 18-19p +
3 &clubs; = 0-2 [red]#&hearts;#, 6+ &clubs;, 16-18p +
3 [red]#&#9670;#, 3&spades; = 0-1 [red]#&#9670;# / &spades;, 4 [red]#&hearts;#, tpv +
3 [red]#&hearts;# = 4 [red]#&hearts;#, 16-18p

| 2 [red]#&hearts;# = 5+ [red]#&hearts;#, 6-10p +

| 1 &clubs;
| 1 [red]#&hearts;# = 4+ &spades;, 6+p
| 1 &spades; = tasan 3&spades;, vaat. +
2 &spades; = 4 &spades;, 11-15p +
2NT = tas., 2-3 &spades;, 18-19p +
3 &clubs; = 0-2 , 6+ &clubs;, 1&spades; 6-18p +
3 [red]#&#9670;#, [red]#&hearts;# = 0-1 [red]#&#9670;# / [red]#&hearts;#, 4 &spades;, tpv +
3 &spades; = 4 &spades;, 16-18p
|
|===

=== Lisää 2/1-sarjoista esimerkein

Alla esimerkkejä sarjoista, joiden kanssa analogiset sarjat
saavat saman merkityksen. Avaajan toinen tarjous kertoo

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 [red]#&hearts;#
| 2&clubs;
| 2 [red]#&hearts;# = min ja ei sivupitoja tai 17+, ei lupaa 6k  [red]#&hearts;#  +
|

|
|
| 2 &spades; = 4+ &spades; , 15+
|

|
|
| 2NT = tasaisehko, pidot tarjoamattomissa väreissä, 11-14 tai 17+
|

|
|
| 3 [red]#&hearts;# = 6+ [red]#&hearts;# , 15 - 16
|

|
|
| 3 &clubs; = 4+ &clubs; , 15+
|

|===

=== Jacoby 2NT
Sopimus on voimassa kahdennuksen jälkeenkin, mutta ei muuten.
|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 1 [red]#&hearts;#
| 2NT = 4+ [red]#&hearts;#, 13+, tpv
| 3&clubs; / 3 [red]#&#9670;# / 3 &spades; = lyhyys tarjotussa värissä, 11+ +
3 [red]#&hearts;# = 6+ [red]#&hearts;# 15+, ei lyhyyttä
3NT = 5 [red]#&hearts;# 422, 16-18 +
4 &clubs; / [red]#&#9670;# = vahva sivuväri, 11+ +
4 [red]#&hearts;# = minimi, ei lyhyyttä
| 3 [red]#&hearts;# = pyytää cueta, muut cue-tarjouksia, ekstraa. 4 [red]#&hearts;# = minimi

| 1 &spades;
| 2NT = 4+ &spades; = 13+
| 3&clubs; / 3 [red]#&#9670;# / 3 [red]#&hearts;# = lyhyys tarjotussa värissä, 11+ +
3 &spades; = 6+ &spades; 15+, ei lyhyyttä
3NT = 5 &spades; 422, 16-18 +
4 &clubs; / [red]#&#9670;# / [red]#&hearts;# = vahva sivuväri, 11+ +
4 [red]#&hearts;# = minimi, ei lyhyyttä
| 3 &spades; = pyytää cueta, muut cue-tarjouksia, ekstraa. +
4 &spades; = minimi

|===




=== Xyz eli 1x - 1y - 1z - jatkot

Xyz-sopimuksella tarjotaan aina kaikki tasaiset ja oman värin
inviitit, jossa sarja on alkanut 1x - 1y - 1z. Sopimus ei ole voimassa, jos vastustaja tekee muuta kuin
passaa. Xyz tarkoittaa mitä tahansa yhden tasolla tapahtuvaa sarjaa, jossa
on kolme tarjousta ja jatko on seuraava.

|===
| Avaaja | Vastaus | Avaaja 2. | Vastaaja 2.

| 1x - 1y - 1z
| 2 &clubs; = pyytää 2 [red]#&#9670;#. Tekee myöhemmin inviitin
tai passaa 2 [red]#&#9670;# tarjoten oman ruutuvärin +

 2 [red]#&#9670;# = keinotekoinen tpv, pyytää kuvaamaan kättä +

 2NT = pyytää tarjoamaan 3 &clubs;, mihin passataan
| 2 [red]#&#9670;#
| Vastaajan värin toisto = inviitti 5+k värillä

|===

==== Esimerkki 1

Alla esimerkki, jossa vastaaja invitoi pitkällä hertallaan.

|===
| Avaaja | Vastaaja

| 1 [red]#&#9670;#
| 1 [red]#&hearts;#

| 1NT
| 2 &clubs; = pyytää tarjoamaan 2 [red]#&#9670;#

| 2 [red]#&#9670;#
| 2 [red]#&hearts;#
|===

==== Esimerkki 2

Alla esimerkki, jossa vastaaja tekee tasaisen inviitin.

|===
| Avaaja | Vastaaja

| 1 [red]#&#9670;#
| 1 [red]#&hearts;#

| 1NT
| 2 &clubs; = pyytää tarjoamaan 2 [red]#&#9670;#

| 2 [red]#&#9670;#
| 2NT = 11-12p
|===

==== Esimerkki 3

Alla esimerkki, jossa vastaaja tekee täyspelin vaatimuksen.

|===
| Avaaja | Vastaaja

| 1 [red]#&#9670;#
| 1 [red]#&hearts;#

| 1NT
| 2 [red]#&#9670;# = keinotekoinen tpv

| 2 [red]#&hearts;# = 3k [red]#&hearts;#
| 3 [red]#&hearts;# = sopii hertan valtiksi, pyytää cue-tarjouksia, slammitriali
|===



== 1NT - jatkot

|===
|Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

|1NT = tas. 15-17
| 2&clubs; = Stayman
| 2 [red]#&#9670;# = ei 4yv
| 2 [red]#&hearts;# = 5 [red]#&hearts;# 4 &spades;, inv. +
2 &spades; = 5 &spades;, 4 [red]#&hearts;#, inv +
3&clubs; = 5+&clubs;, tpv +
3 [red]#&#9670;# = 5+ [red]#&#9670;#, tpv +
3 [red]#&hearts;# = 5+ &spades;, 4 [red]#&hearts;#, tpv +
3 &spades; = 5+ [red]#&hearts;#, 4&spades;, tpv

|
| 2 [red]#&#9670;# = 5+ [red]#&hearts;#, siirto
| 2 [red]#&hearts;# = 2+ [red]#&hearts;# +
3 [red]#&hearts;# = 4+[red]#&hearts;#, max
|

|
| 2 [red]#&hearts;# = 5+ &spades;, siirto +
| 2 &spades; = 2+ &spades; +
3 &spades; = 4+&spades;, max
|

|
| 2 &spades; = 6+&clubs;, kysyy max
| 2NT = min, 3&clubs; = 3+&clubs; max
|

|
| 3&clubs; = 6+ [red]#&#9670;#, siirto
| 3 [red]#&#9670;# = siirto vastaan
| 3yv = lyhyys yv:ssä +
3NT = 15-16p, ei lyhyyksiä

|
| 3 [red]#&#9670;# = 6+ [red]#&#9670;#, inviitti, 8-9p
|
|


|
| 3 [red]#&hearts;# = 3&spades; 1 [red]#&hearts;# av:t 5-4, tpv
|
|

|
| 3&spades; = 3 [red]#&hearts;# 1 &spades; av:t 5-4, tpv
|
|

|
| 4&clubs; = Gerber
| 4 [red]#&#9670;# = 0 / 4 +
4 [red]#&hearts;# = 1 +
4 &spades; = 2 +
4NT = 3
|

|
| 4 [red]#&#9670;# = 6+ [red]#&hearts;# (aina voimassa)
|
|

|
| 4 [red]#&hearts;# = 6+&spades; (aina voimassa)
|
|

|
| 4NT = 16-17p, kvantti
|
|

|===

==  2 &clubs; - jatkot


|===
| Avaus | Vastaus | Avaaja 2. | Vastaaja 2.

| 2 &clubs;
| 2 [red]#&#9670;# = 0+, odottava
| 2NT = tasainen 22-24
| Kuten 2NT-avauksessa


|
| 2 [red]#&hearts;# = 5+ [red]#&hearts;# , 8+
|
|

|
| 2 &spades; = 5+ &spades; , 8+
|
|

|
|2NT = 8+, tasainen
| väritarjous kertoo 5k värin +
  3NT = tasainen 22-24p +
  4NT= 25-26p
|

|
|3 &clubs; = 5+ &clubs; , 8+
|
|

|
| 3 [red]#&#9670;# = 5+ [red]#&#9670;# , 8+
|
|

|===

== Heikkoihin kakkosiin jatkot Ogustilla

Vastaukset ovat voimassa vain, kun vastustaja on passannut tai kahdentanut.

|===
| Avaus | Vastaus | Avaaja 2.

| 2 [red]#&#9670;# / 2 [red]#&hearts;# / 2 &spades;
| 2NT = kysyy, lupaa vähintään inviitin
| 3 &clubs; = min-voima, huono väri +
  3  [red]#&#9670;# = min-voima, hyvä väri +
  3 [red]#&hearts;# = max-voima, huono väri +
  3 &spades; = max-voima, hyvä väri +
  3NT = solidi väri

|===




== 2NT - jatkot

|===
| Avaus | Vastaus | Avaaja 2. | Vastaajan 2.

| 2NT
| 3 &clubs; = Stayman
| 3 [red]#&#9670;# = ei 4k yv
| 3 [red]#&hearts;# = 5+ [red]#&hearts;# 4 &spades;  +
 4 &clubs; = 5+ &clubs; , tpv, avaajan uusi väri kertoo cuen ja tuen. +
 4 [red]#&#9670;# = 5+ [red]#&#9670;# , tpv, avaajan uusi väri on cue ja tuki

|
| 3 [red]#&#9670;# = 5+ [red]#&hearts;# , siirto
| 4 [red]#&hearts;# = 4+ [red]#&hearts;# ja maksimi
|

|
| 3 [red]#&hearts;# = 5+ &spades;, siirto
| 4 &spades; = 4+ &spades; maksimi
|

|
| 3 &spades; = alavärikysely, lupaa av:t, slammihakuinen
| 3NT = ei 4k av
|

|
| 4 &clubs; = Gerber
| 4  [red]#&#9670;# = 0 / 4 ässää +
  4 [red]#&hearts;# = 1 ässä +
  4 &spades; = 2 ässää +
  4 &spades; = 3 ässää
| 4NT = pysäytys +
5 &clubs; = kysyy kuninkaat edelliseen tapaan

|
| 4 [red]#&#9670;# = 6+ [red]#&hearts;# , siirto
|
|

|
| 4 [red]#&hearts;# = 6+ &spades;, siirto
|
|



|===


== Kun vastustaja välitarjoaa

Alla tarjoukset esimerkein. Muut tapaukset käsitellään
vastaavasti.

|===
| Avaaja | Vastustaja | Vastaaja

| 1 [red]#&#9670;#
| Dbl
| Rdbl = 11+, rangaistusluonteinen, ei tukea

|
| 1 [red]#&hearts;#
| Dbl = 4 &spades;, 7+ +
1 &spades; = 5+ &spades;, 6+ +
1NT = 6 - 10 ja pito hertassa +
2 &clubs; = 5+ &clubs;, 11+ +
2 [red]#&#9670;# = 4+, 6 - 10 +
2 [red]#&hearts;# = 4+ [red]#&#9670;#, 11+ +
2NT = pito hertassa, 11-12, ei tukea +
3 [red]#&hearts;# = 0-1 [red]#&hearts;#, 4+[red]#&#9670;#, usein slammihakuinen, tpv

|
| 2 &clubs;
| 2 [red]#&#9670;# = 4+ [red]#&#9670;# , 6 - 10 +
  2 [red]#&hearts;# = 5+ [red]#&hearts;# , 11+, vaatimus +
  2 &spades; = 5+ &spades; , 11+, vaatimus  +
  2NT = 11-12, inviitti ja ristipito +
  3 &clubs; = 4+ [red]#&#9670;# , 11+, vaatimus +




|===

== Lebensohl kolmeen tilanteeseen

Pelaamme Lebensohlia kolmessa paikassa:

1. Kun 1NT-avaustamme häiritään.
2. Kun avaajamme tekee reversen.
3. Kun vastaamme partnerin kahdennukseen, kun avaus
   tapahtui tasolla kaksi.




== Puolustustarjouksia

=== Luonnollisia välitarjouksia

|===
| Vastustaja  | Minä   | 2. Vastustaja | Partneri

| 1 [red]#&#9670;# = 2+ [red]#&#9670;#
| Dbl = 3+k tarjoamattomissa 0-2 [red]#&#9670;#, 12+
  tai vapaa jako ja 18+
| Pass
| 1 [red]#&hearts;# = preffi, 0+ +
  1NT = ruutupito,  6 - 10 +
  2 [red]#&hearts;# = 4+ [red]#&hearts;#, 8 - 11 +
  2NT = ruutupito, 11 - 12

|
| 1 [red]#&hearts;# = 5+ [red]#&hearts;# , 8+
| Pass
| 1 &spades; = 5+ &spades; , hyvä väri, vaatimus, 9+ +
 1NT = ruutupito, 9 - 11 +
 2 [red]#&#9670;# = 3+ [red]#&hearts;#, 11+ +
 3 [red]#&#9670;# = 0-1 [red]#&#9670;# , 4+ [red]#&hearts;#, 13+

|
| 1 &spades; = 5+ &spades; , 8+
|
|

|
| 1NT = ruutupito ja 15 - 18p
| Pass
| Jatkot täsmälleen, kuten avauksessa: <<1NT - jatkot>>


|
| 1NT = ruutupito ja 15 - 18p
| Dbl = rankkari
| luonnolliset jatkot, uusi väri lupaa 4k

|
| 2&clubs; = 5+&clubs;, 12+
|
|

|
| 2 [red]#&hearts;# = 6+ [red]#&hearts;# , esto
|
|

|
| 2 &spades; = 6+ &spades; , esto
|
|

|
| 3 &clubs; = 6+ &clubs; , esto
|
|



|===

=== Michael's cue

|===

| Vastustaja  | Minä   | 2. Vastustaja | Partneri

| 1 &clubs; = 2+ &clubs;
| 2 &clubs; =  5&spades; ja 5k alaväri, 10+
| Pass tai alle 2NT
| 2NT = kysyy alaväriä ja muut tarjoamattomat värit ovat luonnollisia 5k värejä

| 1 [red]#&#9670;# = 2+ [red]#&#9670;#
| 2 [red]#&#9670;# = 5&spades; ja 5k alaväri, 10+
| Pass tai alle 2NT
| 2NT = kysyy alaväriä ja muut tarjoamattomat värit ovat luonnollisia 5k värejä

| 1 [red]#&hearts;# = 2+ [red]#&hearts;#
| 2 [red]#&hearts;# = 5&spades; ja 5k alaväri, 10+
| Pass tai alle 2NT
| 2NT = kysyy alaväriä ja muut tarjoamattomat värit ovat luonnollisia 5k värejä

| 1 &spades; = 2+ &spades;
| 2 &spades; = 5+ [red]#&hearts;# ja 5k av
| Pass tai alle 2NT
| 2NT = kysyy alaväriä ja muut tarjoamattomat värit ovat luonnollisia 5k värejä


|===

=== Unusual 2NT

Vastustaja on avannut yhden tasolla väritarjouksen, joka lupaa vähintään
kaksi korttia. Vain välittömästi tämän jälkeen tarjottu 2NT lupaa
kaksi alinta tarjoamatonta väriä 5-5 ja 10+. Balanssipaikassa tarjottu 2NT
eli (1x) - Pass - (Pass) - 2NT on luonnollinen tasainen 19-22p.

=== (1NT) - puolustus



|===
| Vastustaja | ME

| 1NT
| Dbl = 16+, rankkariluontoinen +

|
| 2 &clubs; = ylävärit 5-4, 9+ +

|
| 2 [red]#&#9670;# = jompikumpi yläväri ja 9+; partnerin 2 [red]#&hearts;#  on passaa tai korjaa +

|
| 2 [red]#&hearts;# = 5+ [red]#&hearts;# ja 4k av, 9+; 2NT partnerilta kysyy alaväriä +

|
| 2 &spades; = 5+ &spades; ja 4k av, 9+ ; partnerin 2NT kysyy alaväriä +

|
| 2NT = alavärit 5-5, 9+

|===

=== Puolustustarjouksia esimerkein


|===
| Vastustaja | Minä | 2. Vastustaja | Partneri

| 1 [red]#&#9670;# = 2+ [red]#&#9670;#
| Dbl = 12+ ja 0-2 [red]#&#9670;#  avausvärissä ja 3+ tarjoamattomissa väreissä
tai jako vapaa ja 18+
| Pass
| 1 [red]#&hearts;# = paras väri, 0 - 7p +
  1 &spades; = paras väri, 0 - 7p +
  1NT = ruutupito, 6 - 10p +
  2 &clubs; = paras väri, 0 - 7p +
  2 [red]#&#9670;# = molemmat ylävärit ja voimaa 11+ +
  2 [red]#&hearts;# = 4+ [red]#&hearts;# , 8 - 11p +
  2NT = ruutupito ja 11-12p +
  3 &clubs; = 4+ &clubs; , 8 - 11p +
  3 [red]#&#9670;# = 4+ [red]#&#9670;# , 8 - 11p +
  3 [red]#&hearts;# = 5+ [red]#&hearts;# , tpv

|
| 1NT = 15 - 18, ruutupito
| Pass
| 1NT-avaussysteemi voimassa

|
| 1NT = 15 - 18, ruutupito
| Dbl = rankkari
| värit luonnollisia


|===



== RKCB

Tarjous 4NT kysyy montako avainkorttia vastaajalla on viidestä. Jos vastaus
ei kerro onko valttirouvaa, niin alin vapaa väri alle valttivärin kysyy valttirouvaa, mihin valttivärin tarjoaminen
viiden tasolla kertoo, että ei ole rouvaa. Muut tarjoukset lupaavat valttirouvan ja sivukuninkaan tarjotussa värissä.
Jos valttirouva löytyy, niin seuraava 5NT kertoo, että meillä on kaikki avainkortit, minkä jälkeen tarjotaan sivukuninkaita vuorotellen alhaalta alkaen ja alle valttivärin.

|===
| Ässäkysely | Vastaus | Kysyjän 2. tarjous | Vastaajan toinen

| 4NT
| 5 &clubs; = 1 tai 4 avainkorttia viidestä
| 5 [red]#&#9670;# = kysyy rouvaa, jos ruutu ei ole valttia
|

|
| 5 [red]#&#9670;# = 0 tai 3 avainkorttia viidestä
|
|

|
| 5 [red]#&hearts;# = 2 tai 5 avainkorttia viidestä ja ei valttirouvaa
|
|

|
| 5 &spades; = 2 tai 5 avainkorttia viidestä ja valttirouva
|
|

|===

== Merkinannot

- Lähdöt 1. tai 3. tai 5.
- Kuninkaalle näytetään pituutta valttipelissä
- 1. sakaus Italialainen
- Lavinthali














