
== Lebensohl / siirrot

=== Meidän 1NT-avauksen jälkeen
Kun vastustaja välitarjoaa ennen partneria, niin partneri
voi käyttää Lebensohlia.

1NT - (2x) - ? +

- Dbl = Stolen bid eli kahdennus on kuin 2x ilman väliintuloa; +
  esimerkiksi jos 2x = 2 &clubs;, niin kahdennus on Stayman
+
- 2NT = pyytää tarjoamaan 3&clubs;. Vastaajalla on aina heikko käsi. 3 &clubs; minkä jälkeen vastaaja passaa tai korjaa loppusitoumukseen +
- 3 &clubs; / 3 [red]#&diams;# / 3 [red]#&hearts;# /  3&spades; = 5+k värin siirto vastaten [red]#&diams;# /  [red]#&hearts;# / &spades; /  &clubs;, 9+p. Vain minimillä  avaaja ottaa siirron vastaan. +

=== Kahdennukseen vastatessa heikon 2x-avauksen jälkeen

Jos avaus 2x on keinotekoinen, niin helpointa on odottaa,
kunnes vastustajat näyttävät värinsä, jolloin selvitään
vähemmällä sopimisella ja voidaan jatkaa tästä. Meidän
passi alussa ei siis kiellä voimaa.

Oletetaan, että sarja on mennyt esim. Multi-avauksella
(2 [red]#&diams;#) - Pass - (2 [red]#&hearts;#) - Pass; +
(Pass) - Dbl ( = normaali ilmaisukahdennus, 12+ ) - (Pass) - ?

- 2&spades; = (3) 4+&spades;, minimi +
- 2NT = pyytää tarjoamaan 3&clubs;. Vastaajalla on joko heikko käsi tai 4&spades; ja pito hertassa. Kahdentava voi tarjota muuta kuin 3 &clubs;, jos hänellä on 19+ +
- 3 &clubs;  = 4+&clubs;, 9-11 +
- 3  [red]#&diams;#   = 4+ [red]#&diams;# , 9-11 +
- 3&spades; = 4+&spades;, 9-11 +

=== Reversen jälkeen

Kun avaaja tekee reversen, niin Lebensohl on käytössä.

Alla esimerkkisarja.

1 &clubs; - 1 [red]#&hearts;#; +
2 [red]#&diams;#  - ? +

- 2 [red]#&hearts;#, värin toisto _kahden_ tasolla 6k väri, ei halua tpv minimiä vastaan
- 2&spades; = 4. väri, kysyy pitoa, tpv +
- 2NT = pyytää tarjoamaan 3&clubs;. Vastaajalla on heikko käsi, 5-7, mihin avaaja voi tarjota muuta jos hänellä on tpv-voima ja muuten +
vastaajan seuraava tarjous on pelattavaksi +
- 3&clubs; = tpv-voima, lisäpituus ristissä (ei kiellä slammivoimaa) +
- 3 [red]#&diams;#  = 4+ [red]#&diams;#, tpv (ei kiellä slammivoimaa) +
- 3 [red]#&hearts;# = (5)6+ [red]#&hearts;#, tpv, +
- 4 &clubs;  =  3+ &clubs; -tuki, slammitriali +
- 4 [red]#&diams;#  = 4+ [red]#&diams;#, slammitriali +

Toinen esimerkki.

1 [red]#&hearts;# - 1NT; +
2 &spades;  - 2NT; +
3 &clubs; - ? +

- Pass = 6+ &clubs; +
- 3 [red]#&diams;# = 6+  [red]#&diams;#, pelattavaksi +
- 3&spades; = 2+&spades; preffi, pelattavaksi +

Kolmas esimerkki.

1 [red]#&hearts;# - 1NT; +
2 &spades;  - 2NT; +
3  [red]#&diams;# = 3+ [red]#&diams;#,  19-21, tpv, koska ei 3 &clubs;  vastaan +


